
const $=x=>document.querySelector(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let devices=[],currentFamilyView=null,familyMode='conclusion';
async function api(url,opt){let r=await fetch(url,opt),j=await r.json();if(!r.ok)throw Error(j.detail||r.status);return j}
function err(e){$('#message').textContent=e.message||String(e)}
function identityEvidence(label,x){return x&&x.value?`${label}：${esc(x.value)}（置信度 ${Math.round((x.confidence||0)*100)}%，第 ${x.page} 页）<br><small>原文：${esc(x.quote)}</small>`:`${label}：未可靠识别，请人工填写`}
function identityModels(models){return (models||[]).length?`<b>规格书覆盖的型号 / 料号候选：</b><ul>${models.map(m=>`<li>${esc(m.value)}${m.scope?' · '+esc(m.scope):''}（第 ${m.page} 页，${Math.round((m.confidence||0)*100)}%）<br><small>${esc(m.quote)}</small></li>`).join('')}</ul>`:'<b>规格书覆盖型号：</b>未可靠识别，可导入后人工补充'}
function documentIdentityPreview(x){if(!x)return '';let v=k=>x[k]?.value||'';return `<b>文档身份（可在上方修改后导入）：</b>${esc(v('document_number')||'未识别')} · ${esc(v('revision')||'版本未识别')}${v('revision_date')?' · '+esc(v('revision_date')):''}${v('document_variant')?' · '+esc(v('document_variant')):''}<br><small>语言：${esc(v('language')||'—')}；该信息用于规格书版本唯一性校验。</small>`}
async function identifyDevice(){let file=$('#pdfFile').files[0];if(!file)return;$('#modelsJson').value='[]';$('#identityStatus').innerHTML='Agent 正在识别厂家、产品族、存储类型和覆盖型号…';try{let fd=new FormData();fd.append('file',file);let r=await api('/api/documents/identify',{method:'POST',body:fd});if(r.vendor?.value)$('#vendor').value=r.vendor.value;if(r.model?.value)$('#model').value=r.model.value;if(r.device_type?.value)$('#deviceType').value=r.device_type.value;let di=r.document_identity||{};if(di.document_number?.value)$('#documentNumber').value=di.document_number.value;if(di.revision?.value)$('#revision').value=di.revision.value;if(di.revision_date?.value)$('#revisionDate').value=di.revision_date.value;if(di.document_variant?.value)$('#documentVariant').value=di.document_variant.value;$('#modelsJson').value=JSON.stringify(r.models||[]);$('#identityStatus').innerHTML=`<b>请确认基础信息后再导入：</b><br>${identityEvidence('厂家',r.vendor)}<br>${identityEvidence('产品族 / 规格',r.model)}<br>${identityEvidence('存储类型',r.device_type)}<br>${identityModels(r.models)}${documentIdentityPreview(r.document_identity)}<br><small>基础信息检查页：${(r.analyzed_pages||[]).join('、')}；型号识别页：${(r.model_analyzed_pages||[]).join('、')}。${r.template?.vendor_template_supported?'已匹配厂家模板：'+esc(r.template.vendor)+' / '+esc(r.template.device_type):'使用通用类型模板'}；参数计划重点读取页：${(r.planned_pages||[]).join('、')||'导入后生成'}。</small>`}catch(e){$('#identityStatus').textContent='自动识别失败：'+(e.message||String(e))+'。可人工填写基础信息后继续导入。'}}
$('#pdfFile').addEventListener('change',identifyDevice);
function renderDeviceRecords(){let h=devices.length?'<table><tr><th>规格书 / 版本</th><th>类型 / 厂家</th><th>识别数据</th><th>操作</th></tr>'+devices.map(d=>`<tr><td><b>${esc(d.model)}</b><br><small>${esc(d.document_number||'文档号未识别')} · ${esc(d.revision||'版本未识别')}${d.revision_date?' · '+esc(d.revision_date):''}<br>${esc(d.filename)} · ${esc(d.page_count||'')} 页 · MD表格 ${d.table_count||0}</small></td><td>${esc(d.device_type)}<br>${esc(d.vendor)}</td><td>型号候选 ${d.model_candidate_count||0} · 原始候选 ${d.candidate_count||0} · 审核后规格 ${d.reviewed_spec_count||0}<br><small>结论：${esc(conclusionStatus(d.conclusion_status||'insufficient'))}</small></td><td><button onclick="openDevice('${esc(d.id)}')">查看</button> <button class="danger" onclick="deleteDevice('${esc(d.id)}')">删除记录</button></td></tr>`).join('')+'</table>':'暂无已导入规格书';$('#deviceRecords').innerHTML=h}
async function refresh(){try{let current=$('#device')?.value||'';devices=await api('/api/devices');let options=devices.map(d=>`<option value="${esc(d.id)}">${esc(d.device_type)} · ${esc(d.vendor)} ${esc(d.model)}</option>`).join('');for(let x of ['device','old','new'])$('#'+x).innerHTML=options;$('#choices').innerHTML=devices.map(d=>`<label><input type="checkbox" class="choice" value="${esc(d.id)}">${esc(d.device_type)} ${esc(d.model)}</label> `).join('');renderDeviceRecords();if(devices.length){if(current&&devices.some(d=>d.id===current))$('#device').value=current;await loadCandidates()}else{$('#familyView').innerHTML='';$('#modelCandidates').innerHTML='';$('#finalReview').innerHTML='';$('#candidates').innerHTML='';}}catch(e){err(e)}}
function setImportProgress(percent,stage,detail,start){$('#importProgress').classList.remove('hidden');$('#importBar').style.width=Math.max(0,Math.min(100,percent||0))+'%';$('#importStage').textContent=stage||'正在处理';$('#importDetail').textContent=detail||'';if(start)$('#importElapsed').textContent=Math.max(0,Math.floor((Date.now()-start)/1000))+' 秒'}
async function waitImportJob(jobId,start){for(;;){let j=await api('/api/documents/jobs/'+jobId);setImportProgress(j.progress,j.status==='failed'?'导入失败':j.status==='completed'?'导入完成':'正在导入',j.message,start);if(j.status==='completed')return j.result;if(j.status==='failed')throw Error(j.error||j.message||'导入失败');await new Promise(r=>setTimeout(r,700))}}
$('#upload').onsubmit=async e=>{e.preventDefault();let btn=$('#importBtn'),start=Date.now();btn.disabled=true;$('#message').textContent='';setImportProgress(1,'准备导入','正在提交 PDF 和确认后的基础信息…',start);try{let job=await api('/api/documents/jobs',{method:'POST',body:new FormData(e.target)});let j=await waitImportJob(job.job_id,start);let mode={agent_template:'Agent + 厂家模板',agent_generic:'Agent + 通用类型模板',agent_unconfigured:'Agent 未配置（不自动使用规则）',rules_opt_in:'规则兜底（显式开启）'}[j.extraction_mode]||j.extraction_mode;setImportProgress(100,'导入完成','已保存规格书、型号候选、参数和证据，正在刷新核对页面…',start);$('#message').textContent=`导入完成：${j.model_candidate_count||0} 个型号候选、${j.candidate_count} 个参数候选，均待人工确认。提取方式：${mode}；重点计划页：${(j.planned_pages||[]).join('、')}；实际分析页：${(j.analyzed_pages||[]).join('、')}。${j.ocr_pages.length?'OCR 页码：'+j.ocr_pages.join('、'):''}${j.candidate_count===0?' 未识别项会继续显示为“待人工补充”，不会被隐藏。':''}`;await refresh();$('#device').value=j.device_id;await loadCandidates();setImportProgress(100,'参数导入完成','参数已进入待核对区；正在执行 最终审核智能体（Final Review Agent） 整体把关…',start);try{await runFinalReview();setImportProgress(100,'全部完成','导入及整体把关已完成，可开始人工核对。',start)}catch(_){setImportProgress(100,'导入完成','参数已导入；Final Review 未完成，可在下方点击“整体把关”重试。',start)}}catch(x){setImportProgress(100,'导入失败',x.message||String(x),start);err(x)}finally{btn.disabled=false}};
function evidence(c){let sid=devices.find(d=>d.id===c.device_id)?.source_id;let evs=(c.evidence&&c.evidence.length)?c.evidence:[{source_page:c.source_page,source_section:c.source_section,source_text:c.source_text,confidence:c.confidence,scope:c.scope}];return evs.map((e,i)=>`<div style="margin-bottom:${i<evs.length-1?'8px':'0'}"><small>证据 ${i+1} · 第 ${e.source_page} 页${e.source_section?' · '+esc(e.source_section):''}${e.scope?' · 适用范围：'+esc(e.scope):''}</small><br><a target="_blank" href="/api/sources/${esc(sid)}/pdf#page=${e.source_page}">查看 PDF 第 ${e.source_page} 页</a>${c.original_url?` · <a target="_blank" href="${esc(c.original_url)}">原始链接</a>`:''}<br>${esc(e.source_text)}</div>`).join('')}
function familyCandidate(c){let sid=devices.find(d=>d.id===$('#device').value)?.source_id;let n=c.evidence_count||1;return `<b>${esc(c.display_value||((c.value||'')+' '+(c.unit||'')).trim())}</b>${c.condition?`<br><small>条件（Condition）：${esc(c.display_condition||c.condition)}</small>`:''}${c.scope?`<br><small>适用范围（Scope）：${esc(c.display_scope||c.scope)}</small>`:''}<br><small>${esc(c.display_status||c.verify_status)} · ${n>1?`证据 ${n} 处`:`第 ${esc(c.source_page||'')} 页`}</small>${sid&&c.source_page?` · <a target="_blank" href="/api/sources/${esc(sid)}/pdf#page=${c.source_page}">查看证据</a>`:''}`}
function matrixCell(items){if(!items||!items.length)return '<span class="muted">—</span>';return items.map(x=>x.reference_common?'<span class="inherit">同公共规格</span>':esc(x.display)).join('<hr style="border:0;border-top:1px solid #eef2f4">')}
function setFamilyMode(mode){familyMode=mode;renderFamilyView(currentFamilyView);if($('#candidates'))$('#candidates').style.display=mode==='raw'?'block':'none'}
function reviewedItems(items){return (items||[]).map(x=>`<div><b>${esc(x.display)}</b>${x.condition?` · ${esc(x.condition)}`:''}${x.scope?`<br><small>适用范围：${esc(x.scope)}</small>`:''}<br><small>${esc(x.display_status||'')} · 证据 ${x.evidence_count||0} 处${x.review_adjusted?' · AI终审已修正候选':''}</small></div>`).join('<hr style="border:0;border-top:1px solid #eef2f4">')}
function conclusionStatus(x){return x==='complete'?'关键信息完整':x==='partial'?'部分信息待补齐':'证据不足'}
function keySpecValues(x){return (x.values||[]).map(v=>`${esc(v.display)}${v.condition?' · '+esc(v.condition):''}${v.scope?'<br><small>适用范围：'+esc(v.scope)+'</small>':''}`).join('<hr style="border:0;border-top:1px solid #eef2f4">')}
function renderConclusionBlock(c){if(!c)return '<span class="muted">尚未形成器件结论。</span>';let risks=(c.risks||[]).length?`<div class="warning-box"><b>待补齐 / 风险</b><ul class="risk-list">${c.risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'';return `<div class="result-banner"><b>寿命与诊断结果 · ${esc(conclusionStatus(c.conclusion_status))}</b> · 结论由审核后规格自动生成，仍需人工确认</div><div class="conclusion-grid"><div class="conclusion-card"><h4>写入寿命结论</h4>${esc(c.lifetime_summary||'—')}</div><div class="conclusion-card"><h4>诊断能力结论</h4>${esc(c.diagnostic_summary||'—')}</div><div class="conclusion-card"><h4>软件关注</h4>${esc(c.software_recommendation||'—')}</div></div>${risks}`}
function renderKeySpecs(c){let a=c?.key_specs||[];if(!a.length)return '<span class="muted">暂未形成关键寿命/诊断规格。</span>';return `<table><tr><th>关键规格</th><th>审核后结果</th><th>级别</th><th>证据</th></tr>${a.map(x=>`<tr><td class="key-spec">${esc(x.parameter_name)}</td><td>${keySpecValues(x)}</td><td>${esc(x.priority||'')}</td><td>${x.evidence_count||0} 处</td></tr>`).join('')}</table>`}
function renderConclusionEvidence(v){let c=v.conclusion||{},a=c.key_specs||[],sid=devices.find(d=>d.id===v.device.id)?.source_id;if(!a.length)return '<span class="muted">暂无关键规格证据。</span>';return a.map(x=>`<details><summary><b>${esc(x.parameter_name)}</b> · ${x.evidence_count||0} 处证据</summary>${(x.evidence||[]).map((e,i)=>`<div style="padding:8px 0;border-bottom:1px solid #eef2f4"><small>证据 ${i+1} · 第 ${esc(e.source_page||'—')} 页${e.source_section?' · '+esc(e.source_section):''}</small><br>${sid&&e.source_page?`<a target="_blank" href="/api/sources/${esc(sid)}/pdf#page=${esc(e.source_page)}">查看 PDF 第 ${esc(e.source_page)} 页</a><br>`:''}${esc(e.source_text||'')}</div>`).join('')}</details>`).join('')}
function renderFamilyView(v){currentFamilyView=v;if(!v){$('#familyView').innerHTML='';return}let c=v.counts||{},rv=v.reviewed||{},di=v.document_identity||{},co=v.conclusion||{},head=`<div class="family-summary"><b>${esc(v.device.vendor)} · ${esc(v.device.product_family)} · ${esc(v.device.device_type)}</b><br><small>${esc(di.document_number||'文档号未识别')} · ${esc(di.revision||'版本未识别')}${di.revision_date?' · '+esc(di.revision_date):''} · 覆盖料号 ${c.models||0} 个 · 关键规格 ${(co.key_specs||[]).length} 项 · 料号差异 ${c.difference_fields||0} 项 · 原始识别明细 ${(v.raw_candidate_count||0)} 条</small></div><div class="tabbar"><button class="${familyMode==='conclusion'?'active':''}" onclick="setFamilyMode('conclusion')">分析结论</button><button class="${familyMode==='key'?'active':''}" onclick="setFamilyMode('key')">关键规格</button><button class="${familyMode==='diff'?'active':''}" onclick="setFamilyMode('diff')">料号差异</button><button class="${familyMode==='evidence'?'active':''}" onclick="setFamilyMode('evidence')">证据</button><button class="${familyMode==='raw'?'active':''}" onclick="setFamilyMode('raw')">识别明细</button></div>`;let body='';if(familyMode==='conclusion'){body=renderConclusionBlock(co)}else if(familyMode==='key'){body=renderKeySpecs(co);body+=`<div class="${rv.review_status==='attention_required'?'warning-box':'family-summary'}" style="margin-top:10px"><b>Final Review：${rv.review_status==='not_run'?'尚未执行':rv.review_status==='attention_required'?'需重点人工检查':'已完成，可进入人工核对'}</b><br><small>${esc(rv.review_summary||'')}</small>${rv.hidden_detail_count?`<br><small>另有 ${rv.hidden_detail_count} 条机制/解释性识别结果位于“识别明细”。</small>`:''}</div>`}else if(familyMode==='diff'){let rows=v.difference_rows||[],models=v.models||[];body=models.length?'<table><tr><th>字段</th>'+models.map(m=>`<th>${esc(m.model)}<br><small>${esc(m.scope||'')}</small></th>`).join('')+'</tr>'+rows.map(r=>`<tr><td>${esc(r.parameter_name)}${r.has_unbound?'<br><span class="badge">有未绑定候选</span>':''}</td>`+models.map(m=>`<td>${matrixCell(r.cells?.[m.id])}</td>`).join('')+'</tr>').join('')+'</table>':'<span class="muted">尚未识别具体料号，暂不能生成料号差异。</span>'}else if(familyMode==='evidence'){body=renderConclusionEvidence(v)}else{body='<div class="muted">下方显示 Agent 原始候选、证据及人工核对操作；该视图用于调试和追溯，不作为默认结果展示。</div>'}$('#familyView').innerHTML=head+body;if($('#candidates'))$('#candidates').style.display=familyMode==='raw'?'block':'none'}
function renderModels(models){let h=(models||[]).length?'<b>规格书覆盖型号 / 料号候选</b><table><tr><th>型号</th><th>适用范围 / 证据</th><th>状态</th></tr>'+models.map(m=>`<tr><td><input id="mv${m.id}" value="${esc(m.final_model??m.ai_model)}"></td><td><input id="ms${m.id}" value="${esc(m.scope||'')}" size="30"><br><small>第 ${m.source_page} 页 · ${esc(m.source_text||'')}</small></td><td>${esc(m.verify_status)}<br><button onclick="reviewModel('${m.id}','confirmed')">确认</button> <button onclick="reviewModel('${m.id}','rejected')">驳回</button></td></tr>`).join('')+'</table>':'<b>规格书覆盖型号：</b>未识别 / 待人工补充';$('#modelCandidates').innerHTML=h}
async function reviewModel(id,status){try{await api('/api/document-models/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,value:$('#mv'+id).value,scope:$('#ms'+id).value,verified_by:$('#reviewer').value})});await loadCandidates()}catch(e){err(e)}}
function renderFinalReview(r,fields=[]){if(!r||r.overall_status==='not_run'){$('#finalReview').innerHTML='<b>最终审核智能体（Final Review Agent）：</b>尚未执行';return}let labels=Object.fromEntries(fields.map(x=>[x.canonical_name,x.parameter_name]));let missing=(r.missing_fields||[]).map(x=>labels[x]||x);let findings=(r.findings||[]).map(f=>`<li><b>${esc(f.severity)} · ${esc(f.category)}</b>${f.canonical_name?' · '+esc(labels[f.canonical_name]||f.canonical_name):''}：${esc(f.message)}<br><small>建议：${esc(f.recommendation)}${(f.candidate_ids||[]).length?' · 关联候选：'+f.candidate_ids.map(esc).join('、'):''}</small></li>`).join('');let corrections=(r.corrections||[]).map(c=>{let before=`${c.old_value||''} ${c.old_unit||''}`.trim(),after=`${c.new_value||''} ${c.new_unit||''}`.trim();return `<div class="review-correction"><b>${c.applied?'已自动修正待确认候选':'修正建议'} · ${esc(c.candidate_id)}</b><br>${esc(before||'—')} → <b>${esc(after||'—')}</b>${c.old_condition!==c.new_condition?`<br><small>条件：${esc(c.old_condition||'—')} → ${esc(c.new_condition||'—')}</small>`:''}${c.old_scope!==c.new_scope?`<br><small>适用范围：${esc(c.old_scope||'—')} → ${esc(c.new_scope||'—')}</small>`:''}<br><small>${esc(c.reason||'')} · ${esc(c.apply_note||'')}</small></div>`}).join('');$('#finalReview').innerHTML=`<b>最终审核智能体（Final Review Agent）：${r.overall_status==='attention_required'?'需重点人工检查':'可进入人工核对'}</b><br>${esc(r.summary||'')}${r.applied_correction_count?`<br><b>已修正 ${r.applied_correction_count} 条待确认候选（仍需人工确认）</b>`:''}${missing.length?`<br><b>未识别字段：</b>${missing.map(esc).join('、')}`:''}${findings?'<ul>'+findings+'</ul>':''}${corrections?'<h4>审核修正记录</h4>'+corrections:''}<small>Final Review 可以修正待确认候选，但不会自动确认；已人工确认的值不会被 AI 覆盖。</small>`}
async function runFinalReview(){let id=$('#device').value;if(!id)return;$('#finalReview').innerHTML='最终审核智能体（Final Review Agent） 正在做完整性、冲突、型号归属和证据一致性检查，并尝试修正有充分证据的待确认候选…';try{let r=await api('/api/devices/'+id+'/final-review',{method:'POST'});await loadCandidates();return r}catch(e){$('#finalReview').textContent='整体审核失败：'+(e.message||String(e));throw e}}
async function loadCandidates(){
  try{
    let id=$('#device').value;if(!id)return;
    let d=devices.find(x=>x.id===id);
    if(!currentFamilyView||currentFamilyView.device?.id!==id)familyMode='conclusion';
    let [a,fields,models,reviewResult,familyView,reviewed]=await Promise.all([api('/api/devices/'+id+'/candidates'),api('/api/spec-fields?device_type='+encodeURIComponent(d.device_type)),api('/api/devices/'+id+'/models'),api('/api/devices/'+id+'/final-review'),api('/api/devices/'+id+'/family-view'),api('/api/devices/'+id+'/reviewed-specs')]);
    familyView.reviewed=reviewed;familyView.raw_candidate_count=a.length;renderFamilyView(familyView);renderModels(models);renderFinalReview(reviewResult,fields);
    let byField={};a.forEach(c=>(byField[c.canonical_name]??=[]).push(c));
    let rows=[];
    for(let f of fields){
      let items=byField[f.canonical_name]||[];
      if(!items.length){
        rows.push(`<tr><td>${esc(f.parameter_name)}</td><td><span class="badge">未识别</span><br><small>Agent 未找到有证据的候选值，可人工查看 PDF 后补充。</small></td><td>—</td><td>待人工补充</td></tr>`);
        continue;
      }
      for(let c of items){
        rows.push(`<tr><td>${esc(c.parameter_name)}<br><small>${String(c.extraction_method).includes('ocr')?'智能体 + OCR（Agent + OCR），需重点核对':(String(c.extraction_method).startsWith('agent_')?'智能体提取（Agent）':'规则提取')}</small></td><td>提取值：${esc(c.display_ai_value||((c.ai_value||'')+' '+(c.ai_unit||'')).trim())}${c.final_value!==null&&c.verify_status==='pending'?`<br><span class="badge">AI终审已修正候选</span> ${esc(c.display_final_value||((c.final_value||'')+' '+(c.final_unit||'')).trim())}`:''}<br><input id="v${c.id}" value="${esc(c.final_value??c.ai_value)}"><input id="u${c.id}" value="${esc(c.final_unit??c.ai_unit)}" size="5"><br><small>条件（Condition）：${esc(c.display_condition||c.condition||'—')}</small><br><input id="cnd${c.id}" value="${esc(c.condition||'')}" size="18"><br><small>适用范围（Scope）：${esc(c.display_scope||c.scope||'—')}</small><br><input id="scp${c.id}" value="${esc(c.scope||'')}" size="24"></td><td>${evidence(c)}</td><td><span class="badge">${esc(c.display_status||c.verify_status)}</span><br><button onclick="review('${c.id}','confirmed')">确认</button> <button onclick="review('${c.id}','rejected')">驳回</button> <button class="danger" onclick="deleteCandidate('${c.id}')">删除</button></td></tr>`);
      }
    }
    $('#candidates').innerHTML='<table><tr><th>标准字段</th><th>候选 / 修正</th><th>证据</th><th>状态 / 操作</th></tr>'+rows.join('')+'</table>';
  }catch(e){err(e)}
}
async function review(id,status){try{await api('/api/candidates/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,value:$('#v'+id).value,unit:$('#u'+id).value,condition:$('#cnd'+id).value,scope:$('#scp'+id).value,verified_by:$('#reviewer').value})});loadCandidates()}catch(e){err(e)}}
async function deleteCandidate(id){if(!confirm('确认删除这条参数候选及其证据吗？已确认参数也会被删除。'))return;try{await api('/api/candidates/'+id,{method:'DELETE'});$('#message').textContent='参数已删除；原 Final Review 已失效，可按需重新整体把关。';await loadCandidates()}catch(e){err(e)}}
async function openDevice(id){$('#device').value=id;await loadCandidates();document.querySelector('#device').scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteDevice(id){let d=devices.find(x=>x.id===id);if(!d)return;let note=`确认删除整条规格书记录吗？\n\n${d.vendor} ${d.model}\n${d.filename}\n\n将删除：型号候选、参数、证据、链接、Final Review，以及该记录独占的本地 PDF。此操作不可撤销。`;if(!confirm(note))return;try{let r=await api('/api/devices/'+id,{method:'DELETE'});$('#message').textContent=`已删除规格书：${r.filename}；参数 ${r.candidate_count} 条、型号候选 ${r.model_candidate_count} 条、链接 ${r.link_count} 条。`;await refresh()}catch(e){err(e)}}
async function deleteCurrentDevice(){let id=$('#device').value;if(id)await deleteDevice(id)}
async function clearCandidates(){let id=$('#device').value;if(!id)return;if(!confirm('确认清空当前规格书的全部参数吗？\n\n会删除参数候选、证据和整体审核结果；PDF、产品族和型号/料号候选会保留。'))return;try{let r=await api('/api/devices/'+id+'/candidates',{method:'DELETE'});$('#message').textContent=`已清空 ${r.deleted_count} 条参数；PDF、产品族和型号/料号候选已保留。`;await loadCandidates()}catch(e){err(e)}}
async function compare(){try{let ids=[...document.querySelectorAll('.choice:checked')].map(x=>x.value),c=await api('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_ids:ids})});$('#comparison').innerHTML='<table><tr><th>字段</th>'+c.devices.map(d=>`<th>${esc(d.model)}</th>`).join('')+'</tr>'+Object.entries(c.fields).map(([k,v])=>`<tr><td>${esc(k)}</td>`+c.devices.map(d=>`<td>${v[d.id]?`${esc(v[d.id].final_value)} ${esc(v[d.id].final_unit)}<br>${evidence(v[d.id])}`:'缺失 / 未确认'}</td>`).join('')+'</tr>').join('')+'</table>'}catch(e){err(e)}}
$('#knowledgeUpload').onsubmit=async e=>{e.preventDefault();try{let r=await api('/api/v1/knowledge/sources',{method:'POST',body:new FormData(e.target)});$('#message').textContent=`资料已索引：${r.passage_count} 个片段，需人工核验后才可检索。`;await loadSources()}catch(x){err(x)}};
$('#knowledgeUrl').onsubmit=async e=>{e.preventDefault();try{let data=Object.fromEntries(new FormData(e.target).entries());let r=await api('/api/v1/knowledge/sources/from-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});$('#message').textContent=r.reused?'已复用相同 URL 和哈希的本地原件。':`官方资料已缓存并索引：${r.passage_count} 个片段，需人工核验。`;await loadSources()}catch(x){err(x)}};
async function loadSources(){try{let a=await api('/api/v1/knowledge/sources');$('#knowledgeSources').innerHTML='<table><tr><th>资料</th><th>状态</th><th>操作</th></tr>'+a.map(s=>`<tr><td><b>${esc(s.title)}</b><br><small>${esc(s.publisher)} · ${esc(s.filename)} · ${s.page_count} 页</small></td><td>${esc(s.verify_status)}<br><small>${esc(s.verified_by||'')}</small></td><td><a target="_blank" href="/api/v1/knowledge/sources/${esc(s.id)}/file">查看原文</a> <button onclick="reviewSource('${esc(s.id)}','verified')">核验通过</button> <button onclick="reviewSource('${esc(s.id)}','rejected')">驳回</button></td></tr>`).join('')+'</table>'}catch(e){err(e)}}
async function reviewSource(id,status){try{await api('/api/v1/knowledge/sources/'+id+'/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,verified_by:$('#knowledgeReviewer').value})});await loadSources()}catch(e){err(e)}}
async function search(){try{let r=await api('/api/v1/knowledge/search?q='+encodeURIComponent($('#query').value));$('#answer').innerHTML='<p>'+esc(r.answer)+'</p>'+r.items.map(item=>{let e=item.evidence;return `<div><b>${item.kind==='confirmed_specification'?'已确认规格':'已核验资料'}</b>：${esc(item.fact)}<br><small>${esc(e.title)} · ${esc(e.publisher)} · 第 ${esc(e.page)} 页 · ${esc(e.verify_status)}</small><br><a target="_blank" href="${esc(e.local_url)}">查看原文</a>${e.official_url?` · <a target="_blank" href="${esc(e.official_url)}">原始链接</a>`:''}<br><small>原文：${esc(e.original_text)}</small></div>`}).join('<hr>')}catch(e){err(e)}}
function claimList(title,items){return items.length?`<h3>${esc(title)}</h3><ul>${items.map(x=>`<li>${esc(x.text)} <small>来源：${x.evidence_ids.map(esc).join('、')}</small></li>`).join('')}</ul>`:''}
function renderAnalysis(r){return `<p><b>${esc(r.status==='no_evidence'?'证据不足':'待工程评审的分析')}</b>：${esc(r.conclusion)}</p>`+claimList('已核验事实',r.facts)+claimList('技术推导',r.inferences)+claimList('软件影响推导',r.software_impacts)+claimList('历史案例',r.historical_context)+(r.unknowns.length?`<h3>待验证</h3><ul>${r.unknowns.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'')+r.evidence.map(e=>`<p><b>${esc(e.id)}</b> · ${esc(e.kind)}：${esc(typeof e.fact==='string'?e.fact:JSON.stringify(e.fact))}<br><small>${esc(JSON.stringify(e.evidence||e.source||{}))}</small>${e.evidence?.local_url?`<br><a target="_blank" href="${esc(e.evidence.local_url)}">查看原文</a>`:''}</p>`).join('')}
async function analyze(){try{let r=await api('/api/v1/ai/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('#query').value})});$('#answer').innerHTML=renderAnalysis(r)}catch(e){err(e)}}
async function impact(){try{let r=await api('/api/v1/ai/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:'比较旧器件与新器件的寿命和接口差异，解释软件配置、监测、异常处理和验证测试的影响，并结合已有资料及历史案例。',old_id:$('#old').value,new_id:$('#new').value})});$('#impact').innerHTML=renderAnalysis(r)}catch(e){err(e)}}
async function searchCases(){try{let a=await api('/api/external/cases?keyword='+encodeURIComponent($('#caseQuery').value));$('#cases').innerHTML=a.map(c=>`<p><b>${esc(c.case_id)}</b> · ${esc(c.summary)}<br>根因：${esc(c.root_cause)}<br>措施：${esc(c.solution)}<br><small>${c.synthetic?'合成演示案例':'外部接口案例'}</small></p>`).join('')||'无匹配案例'}catch(e){err(e)}}
refresh();loadSources();api('/api/v1/ai/status').then(s=>$('#aiStatus').textContent=s.configured?`Agent 已配置：${s.model}（${s.profile||s.provider}）；单次输出上限：${s.max_output_tokens||'由模型决定'} tokens；JSON 模式：${s.json_mode?'开启':'关闭'}。分析内容需工程评审。`:'未配置 Agent；PDF 可导入，但不会自动用规则冒充 Agent 结果，字段将显示为待人工补充。').catch(err);
