from __future__ import annotations
from typing import Literal,Any
from pydantic import Field
from models.common import VersionedDTO, EvidenceReference, Metadata, WarningItem
class EvidenceValue(VersionedDTO):
    value:str='';confidence:float=Field(default=0.0,ge=0,le=1);evidence_type:Literal['EXPLICIT','SUMMARIZED','INFERRED','UNKNOWN']='UNKNOWN';reason:str='';source_refs:list[EvidenceReference]=Field(default_factory=list)
class OpenQuestionDTO(VersionedDTO):
    question_key:str='';question:str;why_it_matters:str='';priority:Literal['HIGH','MEDIUM','LOW']='MEDIUM';answer_type:Literal['TEXT','BOOLEAN','SINGLE_SELECT']='TEXT';suggested_options:list[str]=Field(default_factory=list)
class ClassifiedTermDTO(VersionedDTO):
    code:str='';label_zh:str='';source_type:Literal['SOURCE_DATA','AI_STANDARDIZED','AI_INFERRED','HUMAN_CONFIRMED','UNKNOWN']='UNKNOWN';confidence:float=Field(default=0,ge=0,le=1);evidence:list[EvidenceReference]=Field(default_factory=list)
class MRCConclusionDTO(ClassifiedTermDTO):
    control_status:Literal['DEFINED_EFFECTIVE','DEFINED_INEFFECTIVE','NOT_DEFINED','NOT_EXECUTED','INSUFFICIENT_INFO','UNKNOWN']='UNKNOWN';rationale:str=''
class HardwareComponentDTO(VersionedDTO):
    relevance:Literal['NOT_RELATED','POSSIBLE','CONFIRMED']='POSSIBLE';component_category:str='';component_name:str='';manufacturer:str='';model_part_number:str='';lot_batch:str='';serial_number:str='';board_module:str='';reference_designator:str='';installation_location:str='';hardware_version:str='';failure_mode:str='';failure_mechanism:str='';failure_cause:str='';customer_impact:str='';reproduction_condition:str='';detection_method:str='';disposition:str='';source_type:Literal['SOURCE_DATA','AI_STANDARDIZED','AI_INFERRED','HUMAN_CONFIRMED','UNKNOWN']='UNKNOWN';confidence:float=Field(default=0,ge=0,le=1);evidence:list[EvidenceReference]=Field(default_factory=list)
class OccurrenceAnalysisDTO(VersionedDTO):
    root_cause_summary:EvidenceValue=Field(default_factory=EvidenceValue);failure_mechanism:EvidenceValue=Field(default_factory=EvidenceValue);contributing_factors:list[EvidenceValue]=Field(default_factory=list);occurrence_category:str='';mrc:MRCConclusionDTO=Field(default_factory=MRCConclusionDTO);lifecycle_tags:list[ClassifiedTermDTO]=Field(default_factory=list);issue_type_tags:list[ClassifiedTermDTO]=Field(default_factory=list);hardware_relevance:Literal['NOT_RELATED','POSSIBLE','CONFIRMED']='NOT_RELATED';hardware_components:list[HardwareComponentDTO]=Field(default_factory=list);introduced_phase:str='UNKNOWN';system_scope:dict[str,Any]=Field(default_factory=dict);open_questions:list[OpenQuestionDTO]=Field(default_factory=list);confidence:float=Field(default=0,ge=0,le=1);evidence:list[EvidenceReference]=Field(default_factory=list)
class EscapeAnalysisDTO(VersionedDTO):
    escape_cause_summary:EvidenceValue=Field(default_factory=EvidenceValue);verification_gap:EvidenceValue=Field(default_factory=EvidenceValue);process_gap:EvidenceValue=Field(default_factory=EvidenceValue);escape_category:str='';mrc:MRCConclusionDTO=Field(default_factory=MRCConclusionDTO);lifecycle_tags:list[ClassifiedTermDTO]=Field(default_factory=list);expected_detection_stage:str='UNKNOWN';actual_detection_stage:str='UNKNOWN';missing_control:str='';control_failure_type:str='UNKNOWN';open_questions:list[OpenQuestionDTO]=Field(default_factory=list);confidence:float=Field(default=0,ge=0,le=1);evidence:list[EvidenceReference]=Field(default_factory=list)
class RecurrenceRiskDTO(VersionedDTO):
    recurrence_risk_level:Literal['HIGH','MEDIUM','LOW','UNKNOWN']='UNKNOWN';recurrence_risk_reason:EvidenceValue=Field(default_factory=EvidenceValue);existing_control_coverage:EvidenceValue=Field(default_factory=EvidenceValue);residual_risk:EvidenceValue=Field(default_factory=EvidenceValue);is_common_issue:bool=False;potential_affected_products:list[str]=Field(default_factory=list);horizontal_action_needed:bool=False;customer_impact:dict[str,Any]=Field(default_factory=dict);open_questions:list[OpenQuestionDTO]=Field(default_factory=list)
class CapabilityGapDTO(VersionedDTO):
    gap_id:str='';dimension:Literal['TECHNICAL','MANAGEMENT','GOVERNANCE'];category:str;description:str;why_needed:str='';related_mechanism:str='';recommended_control:str='';recommended_action:str='';action_type:str='';action_target:str='';expected_prevention_effect:str='';scope:str='';affected_products:list[str]=Field(default_factory=list);priority:Literal['P0','P1','P2']='P2';first_action:str='';verification_metric:str='';source_type:Literal['SOURCE_DATA','AI_STANDARDIZED','AI_INFERRED','HUMAN_CONFIRMED','UNKNOWN']='AI_INFERRED';confidence:float=Field(default=0,ge=0,le=1);evidence:list[EvidenceReference]=Field(default_factory=list)
class QualityIssueAnalysisDTO(VersionedDTO):
    knowledge_id:str;occurrence_analysis:OccurrenceAnalysisDTO=Field(default_factory=OccurrenceAnalysisDTO);escape_analysis:EscapeAnalysisDTO=Field(default_factory=EscapeAnalysisDTO);recurrence_analysis:RecurrenceRiskDTO=Field(default_factory=RecurrenceRiskDTO);capability_gaps:list[CapabilityGapDTO]=Field(default_factory=list);warnings:list[WarningItem]=Field(default_factory=list);metadata:Metadata=Field(default_factory=Metadata)
