#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import shutil
import sqlite3
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.build_quality_scenario_test_fixture import build_fixture
OUT = ROOT / "dist"
WORK = ROOT / "validation" / "g1_g5_test_data_package"
PRODUCT_SHA = "80c31f66550e3f9b5c13569da0abb411a526cf59"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def count(conn: sqlite3.Connection, table: str) -> int:
    return int(conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])


def main() -> int:
    shutil.rmtree(WORK, ignore_errors=True)
    WORK.mkdir(parents=True, exist_ok=True)
    OUT.mkdir(parents=True, exist_ok=True)

    db = WORK / "quality_scenario_g1_g5_source.db"
    fixture_manifest = build_fixture(db)
    source_manifest_path = db.with_suffix(db.suffix + ".fixture.json")

    with sqlite3.connect(db) as conn:
        counts = {
            "quality_issue": count(conn, "quality_issue"),
            "software_assessment_record": count(conn, "software_assessment_record"),
            "analysis_run": count(conn, "analysis_run"),
        }

    contract = {
        "contract": "quality-scenario-g1-g5-test-data/v1",
        "test_only": True,
        "product_source_sha": PRODUCT_SHA,
        "data_role": "SOURCE_FACTS_ONLY",
        "preseed_qsv1_candidate": False,
        "preseed_qsv1_review": False,
        "preseed_qsv1_publish": False,
        "cases": [
            "G1_COMPLETE",
            "G2_NO_MISSED_TEST",
            "G3_CONFLICT",
            "G4_DUPLICATE_GENERATE",
            "G5_SOURCE_REVISION",
        ],
        "database": db.name,
        "database_sha256": sha256(db),
        "counts": counts,
        "fixture_contract": fixture_manifest.get("contract"),
    }
    contract_path = WORK / "TEST_DATA_MANIFEST.json"
    contract_path.write_text(json.dumps(contract, ensure_ascii=False, indent=2), encoding="utf-8")

    readme = f"""QUALITY SCENARIO G1-G5 TEST DATA PACKAGE

STATUS=TEST_ONLY
PRODUCT_SOURCE_SHA={PRODUCT_SHA}
DATA_ROLE=SOURCE_FACTS_ONLY

This package is deliberately separate from the product candidate.

It may seed only source-side business facts for G1-G5. It MUST NOT pre-seed:
- QualityScenario V1 Candidate
- Review/Confirm
- Publish
- Portrait projection
- History/lineage results

Expected product path:
  /software-assessment
  -> SourceBundle
  -> Reverse Quality
  -> Candidate
  -> Review / Confirm
  -> Publish
  -> Library / Detail / Portrait

Cases:
- G1_COMPLETE
- G2_NO_MISSED_TEST
- G3_CONFLICT
- G4_DUPLICATE_GENERATE
- G5_SOURCE_REVISION

G5 revision step is generated by the repository tool:
  python tools/build_quality_scenario_test_fixture.py --db <db> --advance-g5

Do not copy this SQLite file into a release/product package.
"""
    (WORK / "README_FIRST.txt").write_text(readme, encoding="utf-8")

    package = OUT / f"QUALITY_SCENARIO_G1_G5_TEST_DATA_{PRODUCT_SHA[:12]}.zip"
    if package.exists():
        package.unlink()
    with zipfile.ZipFile(package, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(WORK.iterdir()):
            zf.write(path, arcname=path.name)

    digest = sha256(package)
    print(f"PRODUCT_SOURCE_SHA={PRODUCT_SHA}")
    print(f"PACKAGE={package.name}")
    print(f"PACKAGE_SHA256={digest}")
    print(f"PACKAGE_SIZE={package.stat().st_size}")
    print(f"DATABASE_SHA256={contract['database_sha256']}")
    print("TEST_ONLY=YES")
    print("PRESEEDED_QSV1_OUTCOMES=NO")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
